name: Deploy Library Management System

on:
  push:
    branches:
      - main  # Trigger on pushes to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install HTMLHint (for validation)
        run: |
          npm install -g htmlhint

      - name: Validate HTML
        run: htmlhint index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .  # Since it's static HTML, deploy current directory
